export const selectInputs = [
  {
    name: "Habit",
    label: "ลักษณะวิสัย",
    options: [
      { value: "Tree", label: "ไม้ต้น" },
      { value: "Shrub", label: "ไม้พุ่ม" },
      { value: "Climber", label: "ไม้เลื้อย" },
      { value: "Herb", label: "ไม้ล้มลุก" },
    ],
  },
  {
    name: "Underground_stem",
    label: "ลำต้นใต้ดิน",
    options: [
      { value: "Rhizome", label: "เหง้า" },
      { value: "Bulb", label: "หัวแบบหัวหอม" },
      { value: "Tuber", label: "หัวแบบมันฝรั่ง" },
      { value: "Corm", label: "หัวแบบเผือก" },
    ],
  },
  {
    name: "Aerial_stem",
    label: "ลำต้นเหนือดิน",
    options: [
      { value: "Twining", label: "ใช้ลำต้นเกี่ยวพัน" },
      { value: "Climbing root", label: "ใช้รากยึดเกาะ" },
      { value: "Tendril", label: "ใช้มือเกาะ" },
      { value: "Creeping", label: "เกาะเลื้อย" },
    ],
  },
  {
    name: "Tree_bark",
    label: "ลำต้น",
    options: [
      { value: "Winged Stem", label: "ลำต้นมีสัน " },
      { value: "No Winged Stem but thorny", label: "ลำต้นไม่มีสัน" },
    ],
  },
  {
    name: "Leaf",
    label: "ใบ",
    options: [{ value: "Simple leaf", label: "ใบเดี่ยว" }],
  },
  {
    name: "Phyllotaxy",
    label: "การเรียงตัวของใบบนกิ่ง",
    options: [
      { value: "Alternate", label: "สลับ" },
      { value: "Opposite", label: "ตรงข้าม" },
      { value: "Distichous", label: "สลับระนาบเดียว" },
      { value: "Decussate", label: "ตรงข้ามสลับตั้งฉาก" },
      { value: "Spiral", label: "เวียน" },
      { value: "Whorled", label: "เป็นวงรอบ" },
    ],
  },
  {
    name: "Leaf_shape",
    label: "รูปร่างแผ่นใบ",
    options: [
      { value: "Subulate", label: "รูปลิ่มแคบ" },
      { value: "Ovate", label: "รูปไข่" },
      { value: "Deltoid", label: "รูปสามเหลี่ยม" },
      { value: "Acicular", label: "รูปเข็ม" },
      { value: "Obovate", label: "รูปไข่กลับ" },
      { value: "Cordate", label: "รูปหัวใจ" },
      { value: "Elliptic", label: "รูปรี" },
      { value: "Orbicular", label: "รูปวงกลม" },
      { value: "Falcate", label: "รูปเคียว" },
      { value: "Oblong", label: "รูปขอบขนาน" },
      { value: "Sagittate", label: "รูปหัวลูกศร" },
      { value: "Hastate", label: "รูปเงี่ยงใบหอก" },
    ],
  },
  {
    name: "Leaf_apex",
    label: "ปลายใบ",
    options: [
      { value: "Acute", label: "แหลม" },
      { value: "Acuminate", label: "เรียวแหลม" },
      { value: "Cuspidate", label: "ติ่งแหลม" },
      { value: "Mucronate", label: "ติ่งหนาม" },
      { value: "Aristate", label: "แหลมเข็ม มีรยางค์แข็ง" },
      { value: "Caudate", label: "ยาวคล้ายหาง" },
      { value: "Cirrate", label: "ม้วน" },
      { value: "Obtuse", label: "มน" },
      { value: "Truncate", label: "ตัด" },
      { value: "Retuse", label: "เว้าบุ๋ม" },
      { value: "Emarginate", label: "เว้าตื้น" },
      { value: "Obcordate", label: "หัวใจกลับ" },
    ],
  },
  {
    name: "Leaf_base",
    label: "โคนใบ",
    options: [
      { value: "Cuneate", label: "รูปลิ่ม" },
      { value: "Attenuate", label: "สอบเรียว" },
      { value: "Oblique", label: "เบี้ยว" },
      { value: "Obtuse", label: "มน" },
      { value: "Truncate", label: "ตัด" },
      { value: "Caudate", label: "รูปหัวใจ" },
      { value: "Sagittate", label: "รูปเงี่ยงลูกศร" },
      { value: "Hastate", label: "รูปเงี่ยงใบหอก" },
      { value: "Auriculate", label: "รูปติ่งหู" },
      { value: "Peltate", label: "แบบก้นปิด" },
      { value: "Perfoliate", label: "รอบข้อ" },
    ],
  },
  {
    name: "Leaf_Margin",
    label: "ขอบใบ",
    options: [
      { value: "Entire", label: "เรียบ" },
      { value: "Undulate", label: "เป็นคลื่น" },
      { value: "Crenate", label: "หยักมน" },
      { value: "Dentate", label: "หยักซี่ฟัน" },
      { value: "Serrate", label: "จักฟันเลื่อย" },
      { value: "Serrulate", label: "จักฟันเลื่อยถี่" },
      { value: "Erose", label: "หยักไม่เป็นระเบียบ" },
      { value: "Ciliate", label: "มีขนครุย" },
      { value: "Lobed", label: "หยัก" },
      { value: "Cleft", label: "เว้าลึก" },
      { value: "Parted", label: "เป็นแฉก" },
      { value: "Divided", label: "หยักลึก" },
    ],
  },
  {
    name: "Flower",
    label: "ดอก",
    options: [
      { value: "Receme", label: "ช่อกระจะ" },
      { value: "Spike", label: "ช่อเชิงลด" },
      { value: "Catkin", label: "ช่อแบบหางกระรอก" },
      { value: "Corymb", label: "ช่อเชิงหลั่น" },
      { value: "Panicle", label: "ช่อแยกแขนง" },
      { value: "Spikelet", label: "ช่อดอกย่อย" },
      { value: "Compound umbel", label: "ช่อซี่ร่มเชิงประกอบ" },
      { value: "Compound dicchasium", label: "ช่อกระจุกเชิงประกอบ" },
    ],
  },
  {
    name: "Position_Flower",
    label: "ตำแหน่งของดอก",
    options: [
      { value: "Terminal", label: "ปลายยอด" },
      { value: "Axillary", label: "ซอกใบ" },
      { value: "Cauliflorous", label: "ตามลำต้นหรือกิ่ง" },
    ],
  },
  {
    name: "Air_potato",
    label: "หัวอากาศ",
    options: [
      { value: "Air potato", label: "มีหัวอากาศ" },
      { value: "Non air potato", label: "ไม่มีหัวอากาศ" },
    ],
  },
  {
    name: "Petiolar_base_color",
    label: "สีของฐานก้าน",
    options: [
      { value: "Purple", label: "ม่วง" },
      { value: "Green", label: "เขียว" },
    ],
  },
  {
    name: "Petiolar_Color",
    label: "สีของก้าน",
    options: [
      { value: "Purple", label: "ม่วง" },
      { value: "Green", label: "เขียว" },
    ],
  },
  {
    name: "Petiolar_apex_color",
    label: "สีของปลายก้าน",
    options: [
      { value: "Purple", label: "ม่วง" },
      { value: "Green", label: "เขียว" },
    ],
  },
];
