# all_class_names = [
#     "A0001", "A0002", "A0003", "A0005", "A0006", "A0010", "A0011", "A0013", "A0014", "A0015",
#     "A0017", "A0018", "A0019", "A0020", "A0021", "A0024", "A0025", "A0029", "A0034", "A0036",
#     "A0037", "A0038", "A0039", "A0040", "A0042", "A0043", "A0046", "A0053", "A0063", "A0064",
#     "A0065", "A0068", "A0072", "A0073", "A0074", "B0001", "B0002", "A0100", "A0101"
# ]

first_layer_class = ["A0000", "B0000", "C0000",
                     "D0000", "E0000", "F0000", "I0000"]

second_layer_class = {
    "A0000": ["A0006", "A0014", "A0015", "A0019", "A0043"],
    "B0000": ["B0065", "B0073"],
    "D0000": ["D0063", "D0068"],
    "F0000": ["F0001", "F0002", "F0003", "F0005", "F0010", "F0020", "F0024", "F0029", "F0039", "F0046", "F0064", "F0074"],
    "I0000": ["I0011", "I0013", "I0017", "I0018", "I0021", "I0025", "I0034", "I0036", "I0037", "I0038", "I0040", "I0042"]
}

# confidence_threshold = 0.3

# filter_data = {
#     "Species": all_class_names,
#     "Habit": [
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Shrub",
#         "Climber",
#         "Climber",
#         "Shrub",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#         "Climber",
#     ],
#     "Underground_stem": [
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data"
#     ],
#     "Aerial_stem": [
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Self Stand",
#         "Twining",
#         "Twining",
#         "Self Stand",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining",
#         "Twining"
#     ],
#     "Tree_bark": [
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#         "No Winged Stem",
#     ],
#     "Leaf": [       # ถุึงนี้แล้งวววว
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf",
#         "Simple leaf"
#     ],
#     "Phyllotaxy": [
#         "Distichous",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Alternate",
#         "Alternate",
#         "Alternate",
#         "Alternate",
#         "Alternate",
#         "Alternate",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Alternate",
#         "Alternate",
#         "Opposite",
#         "Opposite",
#         "Alternate",
#         "Opposite",
#         "Elliptic",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Alternate",
#         "Opposite",
#         "Whorled",
#         "Alternate",
#         "Opposite",
#         "Whorled",
#         "Opposite",
#         "Opposite",
#         "Opposite",
#         "Alternate",
#         "Alternate",
#         "Alternate"
#     ],
#     "Leaf_shape": [
#         "Elliptic",
#         "Elliptic",
#         "Ovate",
#         "Elliptic",
#         "Elliptic",
#         "Ovate",
#         "Elliptic",
#         "Ovate",
#         "Cordate",
#         "Cordate",
#         "Elliptic",
#         "Cordate",
#         "Cordate",
#         "Elliptic",
#         "Ovate",
#         "Cordate",
#         "Elliptic",
#         "Elliptic",
#         "Elliptic",
#         "Elliptic",
#         "Deltoid",
#         "Elliptic",
#         "Elliptic",
#         "Elliptic",
#         "Deltoid",
#         "Elliptic",
#         "Elliptic",
#         "Cordate",
#         "Elliptic",
#         "Cordate",
#         "Elliptic",
#         "Cordate",
#         "Oblong",
#         "Cordate",
#         "Elliptic",
#         "Elliptic",
#         "Cordate",
#         "Cordate",
#         "Cordate"
#     ],
#     "Leaf_apex": [
#         "Acute",
#         "Acute",
#         "Acute",
#         "Acuminate",
#         "Acuminate",
#         "Acuminate",
#         "Acuminate",
#         "Acute",
#         "Acuminate",
#         "Cuspidate",
#         "Acuminate",
#         "Acuminate",
#         "Acute",
#         "Acuminate",
#         "Acuminate",
#         "Acuminate",
#         "Cuspidate",
#         "Acute",
#         "Acuminate",
#         "Cuspidate",
#         "Cuspidate",
#         "Aristate",
#         "Aristate",
#         "Acuminate",
#         "Aristate",
#         "Acuminate",
#         "Acuminate",
#         "Cuspidate",
#         "Acute",
#         "Acuminate",
#         "Acuminate",
#         "Acute",
#         "Acuminate",
#         "Acuminate",
#         "Acuminate",
#         "Acuminate",
#         "Cuspidate",
#         "Acuminate",
#         "Acuminate"
#     ],
#     "Leaf_base": [
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Obtuse",
#         "Cuneate",
#         "Caudate",
#         "Caudate",
#         "Sagittate",
#         "Caudate",
#         "Entire",
#         "Caudate",
#         "Sagittate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Sagittate",
#         "Cuneate",
#         "Caudate",
#         "Caudate",
#         "Obtuse",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate",
#         "Caudate"
#     ],
#     "Leaf_Margin": [
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Crenate",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire",
#         "Entire"

#     ],
#     "Flower": [
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data"
#     ],
#     "Position_Flower": [
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data"
#     ],
#     "Air_potato": [
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "No data",
#         "Air potato",
#         "Air potato"
#     ],
#     "Petiolar_base_color": [  # ถึงตรงนี้
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple",
#         "Purple",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple",
#         "Purple",
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Purple",
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple",
#         "Purple",
#         "Purple",
#         "Purple",
#     ],
#     "Petiolar_color": [
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Purple",
#         "Green",
#         "Green",
#         "Purple",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple"
#     ],
#     "Petiolar_apex_color": [
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple",
#         "Green",
#         "Purple",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Green",
#         "Purple",
#         "Purple",
#         "Purple",
#         "Purple"
#     ]
# }


# for key, value in filter_data.items():
#     print(f"{key:20} -> {len(value)}")
