const mockupData = [
  {
    imageFile: "./uploads/mockupImage/A0006.JPG",
    localName: "มันเสือ",
    leafId: "A0006",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/A0014.JPG",
    localName: "มันอ้อนน้อย",
    leafId: "A0014",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/A0015.JPG",
    localName: "มันแซง",
    leafId: "A0015",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/A0019.JPG",
    localName: "มันทองขาว",
    leafId: "A0019",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/A0043.JPG",
    localName: "มันเห็บ",
    leafId: "A0043",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/B0065.JPG",
    localName: "เอะทวาย",
    leafId: "B0065",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/B0073.JPG",
    localName: "มันกราทราท",
    leafId: "B0073",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/C0000.JPG",
    localName: "มันฤาษี",
    leafId: "C0000",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/D0063.JPG",
    localName: "เอะทรุต",
    leafId: "D0063",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/D0068.JPG",
    localName: "เอะครุต",
    leafId: "D0068",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/E0000.JPG",
    localName: "มันขี้หนู",
    leafId: "E0000",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0001.JPG",
    localName: "หน่อยเกอหน่า",
    leafId: "F0001",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0002.JPG",
    localName: "มันจ้าว",
    leafId: "F0002",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0003.JPG",
    localName: "มันมือเสือ",
    leafId: "F0003",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0005.JPG",
    localName: "มันเหลี่ยม",
    leafId: "F0005",
    role: "OLD",
  },

  {
    imageFile: "./uploads/mockupImage/F0010.JPG",
    localName: "มันกู้",
    leafId: "F0010",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0020.JPG",
    localName: "มันเท้าช้าง",
    leafId: "F0020",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0024.JPG",
    localName: "มันพร้าว",
    leafId: "F0024",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0029.JPG",
    localName: "เอะฮมะนากอก",
    leafId: "F0029",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0039.JPG",
    localName: "มันหวาน",
    leafId: "F0039",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0046.JPG",
    localName: "มันทล่ำ",
    leafId: "F0046",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0064.JPG",
    localName: "มันน้ำ",
    leafId: "F0064",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/F0074.JPG",
    localName: "มันไกว",
    leafId: "F0074",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0011.JPG",
    localName: "มันทองขี้",
    leafId: "I0011",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0013.JPG",
    localName: "มันข้าว",
    leafId: "I0013",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0017.JPG",
    localName: "มันเลือด",
    leafId: "I0017",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0018.JPG",
    localName: "มันแปลง",
    leafId: "I0018",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0021.JPG",
    localName: "มันเหยือก",
    leafId: "I0021",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0025.JPG",
    localName: "มันเหน็บ",
    leafId: "I0025",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0034.JPG",
    localName: "มันเสา",
    leafId: "I0034",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0036.JPG",
    localName: "มันซา",
    leafId: "I0036",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0037.JPG",
    localName: "มันหน่อยซู",
    leafId: "I0037",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0038.JPG",
    localName: "มันหูช้าง",
    leafId: "I0038",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0040.JPG",
    localName: "มันแกลบ",
    leafId: "I0040",
    role: "OLD",
  },
  {
    imageFile: "./uploads/mockupImage/I0042.JPG",
    localName: "มันกุ๊ตี้ (มันทุ๊)",
    leafId: "I0042",
    role: "OLD",
  },
];

module.exports = mockupData
