FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

# อัปเดต pip ก่อนเพื่อช่วย resolve dependency
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "main:app"]
